/*
* generated by Xtext
*/
package net.sf.rcer.rfcgen.ui.contentassist;

import net.sf.rcer.rfcgen.ui.contentassist.AbstractRFCMappingProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RFCMappingProposalProvider extends AbstractRFCMappingProposalProvider {

}
