/*
* generated by Xtext
*/
package net.sf.rcer.rfcgen.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import net.sf.rcer.rfcgen.services.RFCMappingGrammarAccess;

public class RFCMappingParser extends AbstractContentAssistParser {
	
	@Inject
	private RFCMappingGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingLexer createLexer(CharStream stream) {
		return new net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingLexer(stream);
	}
	
	@Override
	protected net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingParser createParser() {
		net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingParser result = new net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				{
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getAlternatives_3(), "rule__StructureFieldPOJOMapping__Alternatives_3");
					put(grammarAccess.getFunctionModulePOJOMappingAccess().getAlternatives(), "rule__FunctionModulePOJOMapping__Alternatives");
					put(grammarAccess.getFunctionModulePOJOParameterMappingAccess().getAlternatives(), "rule__FunctionModulePOJOParameterMapping__Alternatives");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAlternatives_1(), "rule__FunctionModulePOJOImportingParameter__Alternatives_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAlternatives_1_0_3(), "rule__FunctionModulePOJOImportingParameter__Alternatives_1_0_3");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAlternatives_1_1_3(), "rule__FunctionModulePOJOImportingParameter__Alternatives_1_1_3");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAlternatives_1_2_3(), "rule__FunctionModulePOJOImportingParameter__Alternatives_1_2_3");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAlternatives_1(), "rule__FunctionModulePOJOExportingParameter__Alternatives_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAlternatives_1_0_3(), "rule__FunctionModulePOJOExportingParameter__Alternatives_1_0_3");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAlternatives_1_1_3(), "rule__FunctionModulePOJOExportingParameter__Alternatives_1_1_3");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAlternatives_1_2_3(), "rule__FunctionModulePOJOExportingParameter__Alternatives_1_2_3");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAlternatives_1(), "rule__FunctionModulePOJOChangingParameter__Alternatives_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAlternatives_1_0_3(), "rule__FunctionModulePOJOChangingParameter__Alternatives_1_0_3");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAlternatives_1_1_3(), "rule__FunctionModulePOJOChangingParameter__Alternatives_1_1_3");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAlternatives_1_2_3(), "rule__FunctionModulePOJOChangingParameter__Alternatives_1_2_3");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getAlternatives_3(), "rule__FunctionModulePOJOTablesParameter__Alternatives_3");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getStructureAccess().getGroup(), "rule__Structure__Group__0");
					put(grammarAccess.getStructurePOJOMappingAccess().getGroup(), "rule__StructurePOJOMapping__Group__0");
					put(grammarAccess.getStructurePOJOMappingAccess().getGroup_3(), "rule__StructurePOJOMapping__Group_3__0");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getGroup(), "rule__StructureFieldPOJOMapping__Group__0");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getGroup_3_1(), "rule__StructureFieldPOJOMapping__Group_3_1__0");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getGroup_4(), "rule__StructureFieldPOJOMapping__Group_4__0");
					put(grammarAccess.getFunctionModuleAccess().getGroup(), "rule__FunctionModule__Group__0");
					put(grammarAccess.getFunctionModulePOJOCallMappingAccess().getGroup(), "rule__FunctionModulePOJOCallMapping__Group__0");
					put(grammarAccess.getFunctionModulePOJORequestResponseMappingAccess().getGroup(), "rule__FunctionModulePOJORequestResponseMapping__Group__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup(), "rule__FunctionModulePOJOImportingParameter__Group__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_1_0(), "rule__FunctionModulePOJOImportingParameter__Group_1_0__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_1_0_3_1(), "rule__FunctionModulePOJOImportingParameter__Group_1_0_3_1__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_1_1(), "rule__FunctionModulePOJOImportingParameter__Group_1_1__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_1_1_3_1(), "rule__FunctionModulePOJOImportingParameter__Group_1_1_3_1__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_1_2(), "rule__FunctionModulePOJOImportingParameter__Group_1_2__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_1_2_3_1(), "rule__FunctionModulePOJOImportingParameter__Group_1_2_3_1__0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getGroup_2(), "rule__FunctionModulePOJOImportingParameter__Group_2__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup(), "rule__FunctionModulePOJOExportingParameter__Group__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_1_0(), "rule__FunctionModulePOJOExportingParameter__Group_1_0__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_1_0_3_1(), "rule__FunctionModulePOJOExportingParameter__Group_1_0_3_1__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_1_1(), "rule__FunctionModulePOJOExportingParameter__Group_1_1__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_1_1_3_1(), "rule__FunctionModulePOJOExportingParameter__Group_1_1_3_1__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_1_2(), "rule__FunctionModulePOJOExportingParameter__Group_1_2__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_1_2_3_1(), "rule__FunctionModulePOJOExportingParameter__Group_1_2_3_1__0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getGroup_2(), "rule__FunctionModulePOJOExportingParameter__Group_2__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup(), "rule__FunctionModulePOJOChangingParameter__Group__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_1_0(), "rule__FunctionModulePOJOChangingParameter__Group_1_0__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_1_0_3_1(), "rule__FunctionModulePOJOChangingParameter__Group_1_0_3_1__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_1_1(), "rule__FunctionModulePOJOChangingParameter__Group_1_1__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_1_1_3_1(), "rule__FunctionModulePOJOChangingParameter__Group_1_1_3_1__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_1_2(), "rule__FunctionModulePOJOChangingParameter__Group_1_2__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_1_2_3_1(), "rule__FunctionModulePOJOChangingParameter__Group_1_2_3_1__0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getGroup_2(), "rule__FunctionModulePOJOChangingParameter__Group_2__0");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getGroup(), "rule__FunctionModulePOJOTablesParameter__Group__0");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getGroup_3_1(), "rule__FunctionModulePOJOTablesParameter__Group_3_1__0");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getGroup_4(), "rule__FunctionModulePOJOTablesParameter__Group_4__0");
					put(grammarAccess.getModelAccess().getPackageNameAssignment_1(), "rule__Model__PackageNameAssignment_1");
					put(grammarAccess.getModelAccess().getStructuresAssignment_2(), "rule__Model__StructuresAssignment_2");
					put(grammarAccess.getModelAccess().getFunctionModulesAssignment_3(), "rule__Model__FunctionModulesAssignment_3");
					put(grammarAccess.getStructureAccess().getNameAssignment_1(), "rule__Structure__NameAssignment_1");
					put(grammarAccess.getStructureAccess().getMappingAssignment_3(), "rule__Structure__MappingAssignment_3");
					put(grammarAccess.getStructurePOJOMappingAccess().getClassNameAssignment_1(), "rule__StructurePOJOMapping__ClassNameAssignment_1");
					put(grammarAccess.getStructurePOJOMappingAccess().getFieldsAssignment_3_0(), "rule__StructurePOJOMapping__FieldsAssignment_3_0");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getNameAssignment_1(), "rule__StructureFieldPOJOMapping__NameAssignment_1");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getInactiveAssignment_3_0(), "rule__StructureFieldPOJOMapping__InactiveAssignment_3_0");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getTypeAssignment_3_1_0(), "rule__StructureFieldPOJOMapping__TypeAssignment_3_1_0");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getAttributeAssignment_3_1_1(), "rule__StructureFieldPOJOMapping__AttributeAssignment_3_1_1");
					put(grammarAccess.getStructureFieldPOJOMappingAccess().getCommentAssignment_4_1(), "rule__StructureFieldPOJOMapping__CommentAssignment_4_1");
					put(grammarAccess.getFunctionModuleAccess().getNameAssignment_2(), "rule__FunctionModule__NameAssignment_2");
					put(grammarAccess.getFunctionModuleAccess().getMappingAssignment_4(), "rule__FunctionModule__MappingAssignment_4");
					put(grammarAccess.getFunctionModulePOJOCallMappingAccess().getClassNameAssignment_1(), "rule__FunctionModulePOJOCallMapping__ClassNameAssignment_1");
					put(grammarAccess.getFunctionModulePOJOCallMappingAccess().getParametersAssignment_3(), "rule__FunctionModulePOJOCallMapping__ParametersAssignment_3");
					put(grammarAccess.getFunctionModulePOJORequestResponseMappingAccess().getRequestClassNameAssignment_2(), "rule__FunctionModulePOJORequestResponseMapping__RequestClassNameAssignment_2");
					put(grammarAccess.getFunctionModulePOJORequestResponseMappingAccess().getRequestParametersAssignment_4(), "rule__FunctionModulePOJORequestResponseMapping__RequestParametersAssignment_4");
					put(grammarAccess.getFunctionModulePOJORequestResponseMappingAccess().getResponseClassNameAssignment_8(), "rule__FunctionModulePOJORequestResponseMapping__ResponseClassNameAssignment_8");
					put(grammarAccess.getFunctionModulePOJORequestResponseMappingAccess().getResponseParametersAssignment_10(), "rule__FunctionModulePOJORequestResponseMapping__ResponseParametersAssignment_10");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getNameAssignment_1_0_1(), "rule__FunctionModulePOJOImportingParameter__NameAssignment_1_0_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getInactiveAssignment_1_0_3_0(), "rule__FunctionModulePOJOImportingParameter__InactiveAssignment_1_0_3_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getTypeAssignment_1_0_3_1_0(), "rule__FunctionModulePOJOImportingParameter__TypeAssignment_1_0_3_1_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAttributeAssignment_1_0_3_1_1(), "rule__FunctionModulePOJOImportingParameter__AttributeAssignment_1_0_3_1_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getNameAssignment_1_1_1(), "rule__FunctionModulePOJOImportingParameter__NameAssignment_1_1_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getInactiveAssignment_1_1_3_0(), "rule__FunctionModulePOJOImportingParameter__InactiveAssignment_1_1_3_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getStructureAssignment_1_1_3_1_0(), "rule__FunctionModulePOJOImportingParameter__StructureAssignment_1_1_3_1_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAttributeAssignment_1_1_3_1_1(), "rule__FunctionModulePOJOImportingParameter__AttributeAssignment_1_1_3_1_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getTableAssignment_1_2_0(), "rule__FunctionModulePOJOImportingParameter__TableAssignment_1_2_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getNameAssignment_1_2_1(), "rule__FunctionModulePOJOImportingParameter__NameAssignment_1_2_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getInactiveAssignment_1_2_3_0(), "rule__FunctionModulePOJOImportingParameter__InactiveAssignment_1_2_3_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getStructureAssignment_1_2_3_1_0(), "rule__FunctionModulePOJOImportingParameter__StructureAssignment_1_2_3_1_0");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getAttributeAssignment_1_2_3_1_1(), "rule__FunctionModulePOJOImportingParameter__AttributeAssignment_1_2_3_1_1");
					put(grammarAccess.getFunctionModulePOJOImportingParameterAccess().getCommentAssignment_2_1(), "rule__FunctionModulePOJOImportingParameter__CommentAssignment_2_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getNameAssignment_1_0_1(), "rule__FunctionModulePOJOExportingParameter__NameAssignment_1_0_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getInactiveAssignment_1_0_3_0(), "rule__FunctionModulePOJOExportingParameter__InactiveAssignment_1_0_3_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getTypeAssignment_1_0_3_1_0(), "rule__FunctionModulePOJOExportingParameter__TypeAssignment_1_0_3_1_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAttributeAssignment_1_0_3_1_1(), "rule__FunctionModulePOJOExportingParameter__AttributeAssignment_1_0_3_1_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getNameAssignment_1_1_1(), "rule__FunctionModulePOJOExportingParameter__NameAssignment_1_1_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getInactiveAssignment_1_1_3_0(), "rule__FunctionModulePOJOExportingParameter__InactiveAssignment_1_1_3_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getStructureAssignment_1_1_3_1_0(), "rule__FunctionModulePOJOExportingParameter__StructureAssignment_1_1_3_1_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAttributeAssignment_1_1_3_1_1(), "rule__FunctionModulePOJOExportingParameter__AttributeAssignment_1_1_3_1_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getTableAssignment_1_2_0(), "rule__FunctionModulePOJOExportingParameter__TableAssignment_1_2_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getNameAssignment_1_2_1(), "rule__FunctionModulePOJOExportingParameter__NameAssignment_1_2_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getInactiveAssignment_1_2_3_0(), "rule__FunctionModulePOJOExportingParameter__InactiveAssignment_1_2_3_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getStructureAssignment_1_2_3_1_0(), "rule__FunctionModulePOJOExportingParameter__StructureAssignment_1_2_3_1_0");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getAttributeAssignment_1_2_3_1_1(), "rule__FunctionModulePOJOExportingParameter__AttributeAssignment_1_2_3_1_1");
					put(grammarAccess.getFunctionModulePOJOExportingParameterAccess().getCommentAssignment_2_1(), "rule__FunctionModulePOJOExportingParameter__CommentAssignment_2_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getNameAssignment_1_0_1(), "rule__FunctionModulePOJOChangingParameter__NameAssignment_1_0_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getInactiveAssignment_1_0_3_0(), "rule__FunctionModulePOJOChangingParameter__InactiveAssignment_1_0_3_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getTypeAssignment_1_0_3_1_0(), "rule__FunctionModulePOJOChangingParameter__TypeAssignment_1_0_3_1_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAttributeAssignment_1_0_3_1_1(), "rule__FunctionModulePOJOChangingParameter__AttributeAssignment_1_0_3_1_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getNameAssignment_1_1_1(), "rule__FunctionModulePOJOChangingParameter__NameAssignment_1_1_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getInactiveAssignment_1_1_3_0(), "rule__FunctionModulePOJOChangingParameter__InactiveAssignment_1_1_3_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getStructureAssignment_1_1_3_1_0(), "rule__FunctionModulePOJOChangingParameter__StructureAssignment_1_1_3_1_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAttributeAssignment_1_1_3_1_1(), "rule__FunctionModulePOJOChangingParameter__AttributeAssignment_1_1_3_1_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getTableAssignment_1_2_0(), "rule__FunctionModulePOJOChangingParameter__TableAssignment_1_2_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getNameAssignment_1_2_1(), "rule__FunctionModulePOJOChangingParameter__NameAssignment_1_2_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getInactiveAssignment_1_2_3_0(), "rule__FunctionModulePOJOChangingParameter__InactiveAssignment_1_2_3_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getStructureAssignment_1_2_3_1_0(), "rule__FunctionModulePOJOChangingParameter__StructureAssignment_1_2_3_1_0");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getAttributeAssignment_1_2_3_1_1(), "rule__FunctionModulePOJOChangingParameter__AttributeAssignment_1_2_3_1_1");
					put(grammarAccess.getFunctionModulePOJOChangingParameterAccess().getCommentAssignment_2_1(), "rule__FunctionModulePOJOChangingParameter__CommentAssignment_2_1");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getNameAssignment_1(), "rule__FunctionModulePOJOTablesParameter__NameAssignment_1");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getInactiveAssignment_3_0(), "rule__FunctionModulePOJOTablesParameter__InactiveAssignment_3_0");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getStructureAssignment_3_1_0(), "rule__FunctionModulePOJOTablesParameter__StructureAssignment_3_1_0");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getAttributeAssignment_3_1_1(), "rule__FunctionModulePOJOTablesParameter__AttributeAssignment_3_1_1");
					put(grammarAccess.getFunctionModulePOJOTablesParameterAccess().getCommentAssignment_4_1(), "rule__FunctionModulePOJOTablesParameter__CommentAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingParser typedParser = (net.sf.rcer.rfcgen.contentassist.antlr.internal.InternalRFCMappingParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RFCMappingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RFCMappingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
