/*
 * generated by Xtext
 */
package net.sf.rcer.rfcgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RFCMappingUiModule extends net.sf.rcer.rfcgen.ui.AbstractRFCMappingUiModule {
	public RFCMappingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
