/*
* generated by Xtext
*/

package net.sf.rcer.rfcgen.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;

import org.eclipse.xtext.service.GrammarProvider;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RFCMappingGrammarAccess implements IGrammarAccess {
	
	
	public class ModelElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPackageNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPackageNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cPackageNameAssignment_1.eContents().get(0);
		private final Assignment cStructuresAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStructuresStructureParserRuleCall_2_0 = (RuleCall)cStructuresAssignment_2.eContents().get(0);
		private final Assignment cFunctionModulesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFunctionModulesFunctionModuleParserRuleCall_3_0 = (RuleCall)cFunctionModulesAssignment_3.eContents().get(0);
		
		//Model:
		//  "package" packageName=STRING structures+=Structure* functionModules+=FunctionModule
		//  *; 
		//
		//
		//	  
		//	    
		//	    
		//
		//// ====== Structures ==============================================================================
		public ParserRule getRule() { return rule; }

		//"package" packageName=STRING structures+=Structure* functionModules+=FunctionModule
		// *
		public Group getGroup() { return cGroup; }

		//"package"
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }

		//packageName=STRING
		public Assignment getPackageNameAssignment_1() { return cPackageNameAssignment_1; }

		//STRING
		public RuleCall getPackageNameSTRINGTerminalRuleCall_1_0() { return cPackageNameSTRINGTerminalRuleCall_1_0; }

		//structures+=Structure*
		public Assignment getStructuresAssignment_2() { return cStructuresAssignment_2; }

		//Structure
		public RuleCall getStructuresStructureParserRuleCall_2_0() { return cStructuresStructureParserRuleCall_2_0; }

		//functionModules+=FunctionModule*
		public Assignment getFunctionModulesAssignment_3() { return cFunctionModulesAssignment_3; }

		//FunctionModule
		public RuleCall getFunctionModulesFunctionModuleParserRuleCall_3_0() { return cFunctionModulesFunctionModuleParserRuleCall_3_0; }
	}

	public class StructureElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Structure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStructureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMappingAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMappingStructureMappingParserRuleCall_3_0 = (RuleCall)cMappingAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Structure:
		//  "structure" name=STRING "{" mapping=StructureMapping "}"; 
		//
		//// ====== Structures ==============================================================================
		public ParserRule getRule() { return rule; }

		//"structure" name=STRING "{" mapping=StructureMapping "}"
		public Group getGroup() { return cGroup; }

		//"structure"
		public Keyword getStructureKeyword_0() { return cStructureKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//mapping=StructureMapping
		public Assignment getMappingAssignment_3() { return cMappingAssignment_3; }

		//StructureMapping
		public RuleCall getMappingStructureMappingParserRuleCall_3_0() { return cMappingStructureMappingParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class StructureMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StructureMapping");
		private final RuleCall cStructurePOJOMappingParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//StructureMapping:
		//  StructurePOJOMapping; 
		//
		//
		//	
		//
		//// --- POJO mapping -------------------------------------------------------------------------------
		public ParserRule getRule() { return rule; }

		//StructurePOJOMapping
		public RuleCall getStructurePOJOMappingParserRuleCall() { return cStructurePOJOMappingParserRuleCall; }
	}

	public class StructurePOJOMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StructurePOJOMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClassKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cClassNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cClassNameIDTerminalRuleCall_1_0 = (RuleCall)cClassNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFieldsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFieldsStructureFieldPOJOMappingParserRuleCall_3_0 = (RuleCall)cFieldsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//StructurePOJOMapping:
		//  "class" className=ID "{" fields+=StructureFieldPOJOMapping* "}"; 
		//
		//// --- POJO mapping -------------------------------------------------------------------------------
		public ParserRule getRule() { return rule; }

		//"class" className=ID "{" fields+=StructureFieldPOJOMapping* "}"
		public Group getGroup() { return cGroup; }

		//"class"
		public Keyword getClassKeyword_0() { return cClassKeyword_0; }

		//className=ID
		public Assignment getClassNameAssignment_1() { return cClassNameAssignment_1; }

		//ID
		public RuleCall getClassNameIDTerminalRuleCall_1_0() { return cClassNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//fields+=StructureFieldPOJOMapping*
		public Assignment getFieldsAssignment_3() { return cFieldsAssignment_3; }

		//StructureFieldPOJOMapping
		public RuleCall getFieldsStructureFieldPOJOMappingParserRuleCall_3_0() { return cFieldsStructureFieldPOJOMappingParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class StructureFieldPOJOMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StructureFieldPOJOMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeIDTerminalRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Assignment cAttributeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAttributeIDTerminalRuleCall_4_0 = (RuleCall)cAttributeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommentKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCommentAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCommentSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cCommentAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StructureFieldPOJOMapping:
		//  "field" name=STRING "=" type=ID attribute=ID ("comment" comment=STRING)? ";"; 
		//
		//
		//	              
		//
		//// ====== Function Modules ========================================================================
		public ParserRule getRule() { return rule; }

		//"field" name=STRING "=" type=ID attribute=ID ("comment" comment=STRING)? ";"
		public Group getGroup() { return cGroup; }

		//"field"
		public Keyword getFieldKeyword_0() { return cFieldKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//type=ID
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_3_0() { return cTypeIDTerminalRuleCall_3_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_4() { return cAttributeAssignment_4; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_4_0() { return cAttributeIDTerminalRuleCall_4_0; }

		//("comment" comment=STRING)?
		public Group getGroup_5() { return cGroup_5; }

		//"comment"
		public Keyword getCommentKeyword_5_0() { return cCommentKeyword_5_0; }

		//comment=STRING
		public Assignment getCommentAssignment_5_1() { return cCommentAssignment_5_1; }

		//STRING
		public RuleCall getCommentSTRINGTerminalRuleCall_5_1_0() { return cCommentSTRINGTerminalRuleCall_5_1_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}

	public class FunctionModuleElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cModuleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMappingAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMappingFunctionModuleMappingParserRuleCall_4_0 = (RuleCall)cMappingAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FunctionModule:
		//  "function" "module" name=STRING "{" mapping=FunctionModuleMapping "}"; 
		//
		//// ====== Function Modules ========================================================================
		public ParserRule getRule() { return rule; }

		//"function" "module" name=STRING "{" mapping=FunctionModuleMapping "}"
		public Group getGroup() { return cGroup; }

		//"function"
		public Keyword getFunctionKeyword_0() { return cFunctionKeyword_0; }

		//"module"
		public Keyword getModuleKeyword_1() { return cModuleKeyword_1; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//mapping=FunctionModuleMapping
		public Assignment getMappingAssignment_4() { return cMappingAssignment_4; }

		//FunctionModuleMapping
		public RuleCall getMappingFunctionModuleMappingParserRuleCall_4_0() { return cMappingFunctionModuleMappingParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class FunctionModuleMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModuleMapping");
		private final RuleCall cFunctionModulePOJOMappingParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//FunctionModuleMapping:
		//  FunctionModulePOJOMapping; 
		//	
		// 
		//	
		//
		//// --- POJO mapping -------------------------------------------------------------------------------
		public ParserRule getRule() { return rule; }

		//FunctionModulePOJOMapping
		public RuleCall getFunctionModulePOJOMappingParserRuleCall() { return cFunctionModulePOJOMappingParserRuleCall; }
	}

	public class FunctionModulePOJOMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOMapping");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFunctionModulePOJOCallMappingParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionModulePOJORequestResponseMappingParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//FunctionModulePOJOMapping:
		//  FunctionModulePOJOCallMapping|FunctionModulePOJORequestResponseMapping; 
		//
		//// --- POJO mapping -------------------------------------------------------------------------------
		public ParserRule getRule() { return rule; }

		//FunctionModulePOJOCallMapping|FunctionModulePOJORequestResponseMapping 
		//
		//// --- POJO mapping -------------------------------------------------------------------------------
		public Alternatives getAlternatives() { return cAlternatives; }

		//FunctionModulePOJOCallMapping
		public RuleCall getFunctionModulePOJOCallMappingParserRuleCall_0() { return cFunctionModulePOJOCallMappingParserRuleCall_0; }

		//FunctionModulePOJORequestResponseMapping
		public RuleCall getFunctionModulePOJORequestResponseMappingParserRuleCall_1() { return cFunctionModulePOJORequestResponseMappingParserRuleCall_1; }
	}

	public class FunctionModulePOJOCallMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOCallMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClassKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cClassNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cClassNameIDTerminalRuleCall_1_0 = (RuleCall)cClassNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cParametersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParametersFunctionModulePOJOParameterMappingParserRuleCall_3_0 = (RuleCall)cParametersAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FunctionModulePOJOCallMapping:
		//  "class" className=ID "{" parameters+=FunctionModulePOJOParameterMapping* "}";
		public ParserRule getRule() { return rule; }

		//"class" className=ID "{" parameters+=FunctionModulePOJOParameterMapping* "}"
		public Group getGroup() { return cGroup; }

		//"class"
		public Keyword getClassKeyword_0() { return cClassKeyword_0; }

		//className=ID
		public Assignment getClassNameAssignment_1() { return cClassNameAssignment_1; }

		//ID
		public RuleCall getClassNameIDTerminalRuleCall_1_0() { return cClassNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//parameters+=FunctionModulePOJOParameterMapping*
		public Assignment getParametersAssignment_3() { return cParametersAssignment_3; }

		//FunctionModulePOJOParameterMapping
		public RuleCall getParametersFunctionModulePOJOParameterMappingParserRuleCall_3_0() { return cParametersFunctionModulePOJOParameterMappingParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class FunctionModulePOJORequestResponseMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJORequestResponseMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRequestKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRequestClassNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRequestClassNameIDTerminalRuleCall_2_0 = (RuleCall)cRequestClassNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRequestParametersAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRequestParametersFunctionModulePOJOParameterMappingParserRuleCall_4_0 = (RuleCall)cRequestParametersAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cResponseKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cClassKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cResponseClassNameAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cResponseClassNameIDTerminalRuleCall_8_0 = (RuleCall)cResponseClassNameAssignment_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cResponseParametersAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cResponseParametersFunctionModulePOJOParameterMappingParserRuleCall_10_0 = (RuleCall)cResponseParametersAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//FunctionModulePOJORequestResponseMapping:
		//  "request" "class" requestClassName=ID "{" requestParameters+=
		//  FunctionModulePOJOParameterMapping* "}" "response" "class" responseClassName=ID "{"
		//  responseParameters+=FunctionModulePOJOParameterMapping* "}";
		public ParserRule getRule() { return rule; }

		//"request" "class" requestClassName=ID "{" requestParameters+=
		//FunctionModulePOJOParameterMapping* "}" "response" "class" responseClassName=ID "{"
		//responseParameters+=FunctionModulePOJOParameterMapping* "}"
		public Group getGroup() { return cGroup; }

		//"request"
		public Keyword getRequestKeyword_0() { return cRequestKeyword_0; }

		//"class"
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }

		//requestClassName=ID
		public Assignment getRequestClassNameAssignment_2() { return cRequestClassNameAssignment_2; }

		//ID
		public RuleCall getRequestClassNameIDTerminalRuleCall_2_0() { return cRequestClassNameIDTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//requestParameters+=FunctionModulePOJOParameterMapping*
		public Assignment getRequestParametersAssignment_4() { return cRequestParametersAssignment_4; }

		//FunctionModulePOJOParameterMapping
		public RuleCall getRequestParametersFunctionModulePOJOParameterMappingParserRuleCall_4_0() { return cRequestParametersFunctionModulePOJOParameterMappingParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }

		//"response"
		public Keyword getResponseKeyword_6() { return cResponseKeyword_6; }

		//"class"
		public Keyword getClassKeyword_7() { return cClassKeyword_7; }

		//responseClassName=ID
		public Assignment getResponseClassNameAssignment_8() { return cResponseClassNameAssignment_8; }

		//ID
		public RuleCall getResponseClassNameIDTerminalRuleCall_8_0() { return cResponseClassNameIDTerminalRuleCall_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }

		//responseParameters+=FunctionModulePOJOParameterMapping*
		public Assignment getResponseParametersAssignment_10() { return cResponseParametersAssignment_10; }

		//FunctionModulePOJOParameterMapping
		public RuleCall getResponseParametersFunctionModulePOJOParameterMappingParserRuleCall_10_0() { return cResponseParametersFunctionModulePOJOParameterMappingParserRuleCall_10_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class FunctionModulePOJOParameterMappingElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOParameterMapping");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFunctionModulePOJOImportingParameterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionModulePOJOExportingParameterParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFunctionModulePOJOChangingParameterParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFunctionModulePOJOTablesParameterParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//FunctionModulePOJOParameterMapping:
		//  FunctionModulePOJOImportingParameter|FunctionModulePOJOExportingParameter|
		//  FunctionModulePOJOChangingParameter|FunctionModulePOJOTablesParameter;
		public ParserRule getRule() { return rule; }

		//FunctionModulePOJOImportingParameter|FunctionModulePOJOExportingParameter|
		//FunctionModulePOJOChangingParameter|FunctionModulePOJOTablesParameter
		public Alternatives getAlternatives() { return cAlternatives; }

		//FunctionModulePOJOImportingParameter
		public RuleCall getFunctionModulePOJOImportingParameterParserRuleCall_0() { return cFunctionModulePOJOImportingParameterParserRuleCall_0; }

		//FunctionModulePOJOExportingParameter
		public RuleCall getFunctionModulePOJOExportingParameterParserRuleCall_1() { return cFunctionModulePOJOExportingParameterParserRuleCall_1; }

		//FunctionModulePOJOChangingParameter
		public RuleCall getFunctionModulePOJOChangingParameterParserRuleCall_2() { return cFunctionModulePOJOChangingParameterParserRuleCall_2; }

		//FunctionModulePOJOTablesParameter
		public RuleCall getFunctionModulePOJOTablesParameterParserRuleCall_3() { return cFunctionModulePOJOTablesParameterParserRuleCall_3; }
	}

	public class FunctionModulePOJOImportingParameterElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOImportingParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cFieldKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0_1_0 = (RuleCall)cNameAssignment_1_0_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_2 = (Keyword)cGroup_1_0.eContents().get(2);
		private final Alternatives cAlternatives_1_0_3 = (Alternatives)cGroup_1_0.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_0_3_0 = (Assignment)cAlternatives_1_0_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_0_3_0_0 = (Keyword)cIsInactiveAssignment_1_0_3_0.eContents().get(0);
		private final Group cGroup_1_0_3_1 = (Group)cAlternatives_1_0_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_0_3_1_0 = (Assignment)cGroup_1_0_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_0_3_1_0_0 = (RuleCall)cTypeAssignment_1_0_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_0_3_1_1 = (Assignment)cGroup_1_0_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_0_3_1_1_0 = (RuleCall)cAttributeAssignment_1_0_3_1_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cIsStructureAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final Keyword cIsStructureStructureKeyword_1_1_0_0 = (Keyword)cIsStructureAssignment_1_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_1_1_0 = (RuleCall)cNameAssignment_1_1_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Alternatives cAlternatives_1_1_3 = (Alternatives)cGroup_1_1.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_1_3_0 = (Assignment)cAlternatives_1_1_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_1_3_0_0 = (Keyword)cIsInactiveAssignment_1_1_3_0.eContents().get(0);
		private final Group cGroup_1_1_3_1 = (Group)cAlternatives_1_1_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_1_3_1_0 = (Assignment)cGroup_1_1_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_1_3_1_0_0 = (RuleCall)cTypeAssignment_1_1_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_1_3_1_1 = (Assignment)cGroup_1_1_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_1_3_1_1_0 = (RuleCall)cAttributeAssignment_1_1_3_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Assignment cIsTableAssignment_1_2_0 = (Assignment)cGroup_1_2.eContents().get(0);
		private final Keyword cIsTableTableKeyword_1_2_0_0 = (Keyword)cIsTableAssignment_1_2_0.eContents().get(0);
		private final Assignment cNameAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_2_1_0 = (RuleCall)cNameAssignment_1_2_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_2_2 = (Keyword)cGroup_1_2.eContents().get(2);
		private final Alternatives cAlternatives_1_2_3 = (Alternatives)cGroup_1_2.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_2_3_0 = (Assignment)cAlternatives_1_2_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_2_3_0_0 = (Keyword)cIsInactiveAssignment_1_2_3_0.eContents().get(0);
		private final Group cGroup_1_2_3_1 = (Group)cAlternatives_1_2_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_2_3_1_0 = (Assignment)cGroup_1_2_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_2_3_1_0_0 = (RuleCall)cTypeAssignment_1_2_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_2_3_1_1 = (Assignment)cGroup_1_2_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_2_3_1_1_0 = (RuleCall)cAttributeAssignment_1_2_3_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommentKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCommentAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCommentSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cCommentAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FunctionModulePOJOImportingParameter:
		//  "import" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
		//  isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//  ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
		//  "comment" comment=STRING)? ";";
		public ParserRule getRule() { return rule; }

		//"import" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
		//isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
		//"comment" comment=STRING)? ";"
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//"field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|isStructure?=
		//"structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|isTable?=
		//"table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"field"
		public Keyword getFieldKeyword_1_0_0() { return cFieldKeyword_1_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_0_1() { return cNameAssignment_1_0_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0_1_0() { return cNameSTRINGTerminalRuleCall_1_0_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_0_2() { return cEqualsSignKeyword_1_0_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_0_3() { return cAlternatives_1_0_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_0_3_0() { return cIsInactiveAssignment_1_0_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_0_3_0_0() { return cIsInactiveInactiveKeyword_1_0_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_0_3_1() { return cGroup_1_0_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_0_3_1_0() { return cTypeAssignment_1_0_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_0_3_1_0_0() { return cTypeIDTerminalRuleCall_1_0_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_0_3_1_1() { return cAttributeAssignment_1_0_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_0_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_0_3_1_1_0; }

		//isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//ID)
		public Group getGroup_1_1() { return cGroup_1_1; }

		//isStructure?="structure"
		public Assignment getIsStructureAssignment_1_1_0() { return cIsStructureAssignment_1_1_0; }

		//"structure"
		public Keyword getIsStructureStructureKeyword_1_1_0_0() { return cIsStructureStructureKeyword_1_1_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_1_1() { return cNameAssignment_1_1_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_1_1_0() { return cNameSTRINGTerminalRuleCall_1_1_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1_2() { return cEqualsSignKeyword_1_1_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_1_3() { return cAlternatives_1_1_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_1_3_0() { return cIsInactiveAssignment_1_1_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_1_3_0_0() { return cIsInactiveInactiveKeyword_1_1_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_1_3_1() { return cGroup_1_1_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_1_3_1_0() { return cTypeAssignment_1_1_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_1_3_1_0_0() { return cTypeIDTerminalRuleCall_1_1_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_1_3_1_1() { return cAttributeAssignment_1_1_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_1_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_1_3_1_1_0; }

		//isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Group getGroup_1_2() { return cGroup_1_2; }

		//isTable?="table"
		public Assignment getIsTableAssignment_1_2_0() { return cIsTableAssignment_1_2_0; }

		//"table"
		public Keyword getIsTableTableKeyword_1_2_0_0() { return cIsTableTableKeyword_1_2_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_2_1() { return cNameAssignment_1_2_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_2_1_0() { return cNameSTRINGTerminalRuleCall_1_2_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_2_2() { return cEqualsSignKeyword_1_2_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_2_3() { return cAlternatives_1_2_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_2_3_0() { return cIsInactiveAssignment_1_2_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_2_3_0_0() { return cIsInactiveInactiveKeyword_1_2_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_2_3_1() { return cGroup_1_2_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_2_3_1_0() { return cTypeAssignment_1_2_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_2_3_1_0_0() { return cTypeIDTerminalRuleCall_1_2_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_2_3_1_1() { return cAttributeAssignment_1_2_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_2_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_2_3_1_1_0; }

		//("comment" comment=STRING)?
		public Group getGroup_2() { return cGroup_2; }

		//"comment"
		public Keyword getCommentKeyword_2_0() { return cCommentKeyword_2_0; }

		//comment=STRING
		public Assignment getCommentAssignment_2_1() { return cCommentAssignment_2_1; }

		//STRING
		public RuleCall getCommentSTRINGTerminalRuleCall_2_1_0() { return cCommentSTRINGTerminalRuleCall_2_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class FunctionModulePOJOExportingParameterElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOExportingParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cFieldKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0_1_0 = (RuleCall)cNameAssignment_1_0_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_2 = (Keyword)cGroup_1_0.eContents().get(2);
		private final Alternatives cAlternatives_1_0_3 = (Alternatives)cGroup_1_0.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_0_3_0 = (Assignment)cAlternatives_1_0_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_0_3_0_0 = (Keyword)cIsInactiveAssignment_1_0_3_0.eContents().get(0);
		private final Group cGroup_1_0_3_1 = (Group)cAlternatives_1_0_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_0_3_1_0 = (Assignment)cGroup_1_0_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_0_3_1_0_0 = (RuleCall)cTypeAssignment_1_0_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_0_3_1_1 = (Assignment)cGroup_1_0_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_0_3_1_1_0 = (RuleCall)cAttributeAssignment_1_0_3_1_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cIsStructureAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final Keyword cIsStructureStructureKeyword_1_1_0_0 = (Keyword)cIsStructureAssignment_1_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_1_1_0 = (RuleCall)cNameAssignment_1_1_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Alternatives cAlternatives_1_1_3 = (Alternatives)cGroup_1_1.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_1_3_0 = (Assignment)cAlternatives_1_1_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_1_3_0_0 = (Keyword)cIsInactiveAssignment_1_1_3_0.eContents().get(0);
		private final Group cGroup_1_1_3_1 = (Group)cAlternatives_1_1_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_1_3_1_0 = (Assignment)cGroup_1_1_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_1_3_1_0_0 = (RuleCall)cTypeAssignment_1_1_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_1_3_1_1 = (Assignment)cGroup_1_1_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_1_3_1_1_0 = (RuleCall)cAttributeAssignment_1_1_3_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Assignment cIsTableAssignment_1_2_0 = (Assignment)cGroup_1_2.eContents().get(0);
		private final Keyword cIsTableTableKeyword_1_2_0_0 = (Keyword)cIsTableAssignment_1_2_0.eContents().get(0);
		private final Assignment cNameAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_2_1_0 = (RuleCall)cNameAssignment_1_2_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_2_2 = (Keyword)cGroup_1_2.eContents().get(2);
		private final Alternatives cAlternatives_1_2_3 = (Alternatives)cGroup_1_2.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_2_3_0 = (Assignment)cAlternatives_1_2_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_2_3_0_0 = (Keyword)cIsInactiveAssignment_1_2_3_0.eContents().get(0);
		private final Group cGroup_1_2_3_1 = (Group)cAlternatives_1_2_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_2_3_1_0 = (Assignment)cGroup_1_2_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_2_3_1_0_0 = (RuleCall)cTypeAssignment_1_2_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_2_3_1_1 = (Assignment)cGroup_1_2_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_2_3_1_1_0 = (RuleCall)cAttributeAssignment_1_2_3_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommentKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCommentAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCommentSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cCommentAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FunctionModulePOJOExportingParameter:
		//  "export" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
		//  isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//  ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
		//  "comment" comment=STRING)? ";";
		public ParserRule getRule() { return rule; }

		//"export" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
		//isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
		//"comment" comment=STRING)? ";"
		public Group getGroup() { return cGroup; }

		//"export"
		public Keyword getExportKeyword_0() { return cExportKeyword_0; }

		//"field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|isStructure?=
		//"structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|isTable?=
		//"table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"field"
		public Keyword getFieldKeyword_1_0_0() { return cFieldKeyword_1_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_0_1() { return cNameAssignment_1_0_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0_1_0() { return cNameSTRINGTerminalRuleCall_1_0_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_0_2() { return cEqualsSignKeyword_1_0_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_0_3() { return cAlternatives_1_0_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_0_3_0() { return cIsInactiveAssignment_1_0_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_0_3_0_0() { return cIsInactiveInactiveKeyword_1_0_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_0_3_1() { return cGroup_1_0_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_0_3_1_0() { return cTypeAssignment_1_0_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_0_3_1_0_0() { return cTypeIDTerminalRuleCall_1_0_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_0_3_1_1() { return cAttributeAssignment_1_0_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_0_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_0_3_1_1_0; }

		//isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//ID)
		public Group getGroup_1_1() { return cGroup_1_1; }

		//isStructure?="structure"
		public Assignment getIsStructureAssignment_1_1_0() { return cIsStructureAssignment_1_1_0; }

		//"structure"
		public Keyword getIsStructureStructureKeyword_1_1_0_0() { return cIsStructureStructureKeyword_1_1_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_1_1() { return cNameAssignment_1_1_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_1_1_0() { return cNameSTRINGTerminalRuleCall_1_1_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1_2() { return cEqualsSignKeyword_1_1_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_1_3() { return cAlternatives_1_1_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_1_3_0() { return cIsInactiveAssignment_1_1_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_1_3_0_0() { return cIsInactiveInactiveKeyword_1_1_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_1_3_1() { return cGroup_1_1_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_1_3_1_0() { return cTypeAssignment_1_1_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_1_3_1_0_0() { return cTypeIDTerminalRuleCall_1_1_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_1_3_1_1() { return cAttributeAssignment_1_1_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_1_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_1_3_1_1_0; }

		//isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Group getGroup_1_2() { return cGroup_1_2; }

		//isTable?="table"
		public Assignment getIsTableAssignment_1_2_0() { return cIsTableAssignment_1_2_0; }

		//"table"
		public Keyword getIsTableTableKeyword_1_2_0_0() { return cIsTableTableKeyword_1_2_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_2_1() { return cNameAssignment_1_2_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_2_1_0() { return cNameSTRINGTerminalRuleCall_1_2_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_2_2() { return cEqualsSignKeyword_1_2_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_2_3() { return cAlternatives_1_2_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_2_3_0() { return cIsInactiveAssignment_1_2_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_2_3_0_0() { return cIsInactiveInactiveKeyword_1_2_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_2_3_1() { return cGroup_1_2_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_2_3_1_0() { return cTypeAssignment_1_2_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_2_3_1_0_0() { return cTypeIDTerminalRuleCall_1_2_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_2_3_1_1() { return cAttributeAssignment_1_2_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_2_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_2_3_1_1_0; }

		//("comment" comment=STRING)?
		public Group getGroup_2() { return cGroup_2; }

		//"comment"
		public Keyword getCommentKeyword_2_0() { return cCommentKeyword_2_0; }

		//comment=STRING
		public Assignment getCommentAssignment_2_1() { return cCommentAssignment_2_1; }

		//STRING
		public RuleCall getCommentSTRINGTerminalRuleCall_2_1_0() { return cCommentSTRINGTerminalRuleCall_2_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class FunctionModulePOJOChangingParameterElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOChangingParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChangeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cFieldKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0_1_0 = (RuleCall)cNameAssignment_1_0_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_2 = (Keyword)cGroup_1_0.eContents().get(2);
		private final Alternatives cAlternatives_1_0_3 = (Alternatives)cGroup_1_0.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_0_3_0 = (Assignment)cAlternatives_1_0_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_0_3_0_0 = (Keyword)cIsInactiveAssignment_1_0_3_0.eContents().get(0);
		private final Group cGroup_1_0_3_1 = (Group)cAlternatives_1_0_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_0_3_1_0 = (Assignment)cGroup_1_0_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_0_3_1_0_0 = (RuleCall)cTypeAssignment_1_0_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_0_3_1_1 = (Assignment)cGroup_1_0_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_0_3_1_1_0 = (RuleCall)cAttributeAssignment_1_0_3_1_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cIsStructureAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final Keyword cIsStructureStructureKeyword_1_1_0_0 = (Keyword)cIsStructureAssignment_1_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_1_1_0 = (RuleCall)cNameAssignment_1_1_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Alternatives cAlternatives_1_1_3 = (Alternatives)cGroup_1_1.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_1_3_0 = (Assignment)cAlternatives_1_1_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_1_3_0_0 = (Keyword)cIsInactiveAssignment_1_1_3_0.eContents().get(0);
		private final Group cGroup_1_1_3_1 = (Group)cAlternatives_1_1_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_1_3_1_0 = (Assignment)cGroup_1_1_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_1_3_1_0_0 = (RuleCall)cTypeAssignment_1_1_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_1_3_1_1 = (Assignment)cGroup_1_1_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_1_3_1_1_0 = (RuleCall)cAttributeAssignment_1_1_3_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Assignment cIsTableAssignment_1_2_0 = (Assignment)cGroup_1_2.eContents().get(0);
		private final Keyword cIsTableTableKeyword_1_2_0_0 = (Keyword)cIsTableAssignment_1_2_0.eContents().get(0);
		private final Assignment cNameAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_2_1_0 = (RuleCall)cNameAssignment_1_2_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_2_2 = (Keyword)cGroup_1_2.eContents().get(2);
		private final Alternatives cAlternatives_1_2_3 = (Alternatives)cGroup_1_2.eContents().get(3);
		private final Assignment cIsInactiveAssignment_1_2_3_0 = (Assignment)cAlternatives_1_2_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_1_2_3_0_0 = (Keyword)cIsInactiveAssignment_1_2_3_0.eContents().get(0);
		private final Group cGroup_1_2_3_1 = (Group)cAlternatives_1_2_3.eContents().get(1);
		private final Assignment cTypeAssignment_1_2_3_1_0 = (Assignment)cGroup_1_2_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_1_2_3_1_0_0 = (RuleCall)cTypeAssignment_1_2_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_1_2_3_1_1 = (Assignment)cGroup_1_2_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_1_2_3_1_1_0 = (RuleCall)cAttributeAssignment_1_2_3_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommentKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCommentAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCommentSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cCommentAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FunctionModulePOJOChangingParameter:
		//  "change" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
		//  isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//  ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
		//  "comment" comment=STRING)? ";";
		public ParserRule getRule() { return rule; }

		//"change" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
		//isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
		//"comment" comment=STRING)? ";"
		public Group getGroup() { return cGroup; }

		//"change"
		public Keyword getChangeKeyword_0() { return cChangeKeyword_0; }

		//"field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|isStructure?=
		//"structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|isTable?=
		//"table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"field"
		public Keyword getFieldKeyword_1_0_0() { return cFieldKeyword_1_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_0_1() { return cNameAssignment_1_0_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0_1_0() { return cNameSTRINGTerminalRuleCall_1_0_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_0_2() { return cEqualsSignKeyword_1_0_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_0_3() { return cAlternatives_1_0_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_0_3_0() { return cIsInactiveAssignment_1_0_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_0_3_0_0() { return cIsInactiveInactiveKeyword_1_0_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_0_3_1() { return cGroup_1_0_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_0_3_1_0() { return cTypeAssignment_1_0_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_0_3_1_0_0() { return cTypeIDTerminalRuleCall_1_0_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_0_3_1_1() { return cAttributeAssignment_1_0_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_0_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_0_3_1_1_0; }

		//isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
		//ID)
		public Group getGroup_1_1() { return cGroup_1_1; }

		//isStructure?="structure"
		public Assignment getIsStructureAssignment_1_1_0() { return cIsStructureAssignment_1_1_0; }

		//"structure"
		public Keyword getIsStructureStructureKeyword_1_1_0_0() { return cIsStructureStructureKeyword_1_1_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_1_1() { return cNameAssignment_1_1_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_1_1_0() { return cNameSTRINGTerminalRuleCall_1_1_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1_2() { return cEqualsSignKeyword_1_1_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_1_3() { return cAlternatives_1_1_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_1_3_0() { return cIsInactiveAssignment_1_1_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_1_3_0_0() { return cIsInactiveInactiveKeyword_1_1_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_1_3_1() { return cGroup_1_1_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_1_3_1_0() { return cTypeAssignment_1_1_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_1_3_1_0_0() { return cTypeIDTerminalRuleCall_1_1_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_1_3_1_1() { return cAttributeAssignment_1_1_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_1_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_1_3_1_1_0; }

		//isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)
		public Group getGroup_1_2() { return cGroup_1_2; }

		//isTable?="table"
		public Assignment getIsTableAssignment_1_2_0() { return cIsTableAssignment_1_2_0; }

		//"table"
		public Keyword getIsTableTableKeyword_1_2_0_0() { return cIsTableTableKeyword_1_2_0_0; }

		//name=STRING
		public Assignment getNameAssignment_1_2_1() { return cNameAssignment_1_2_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_2_1_0() { return cNameSTRINGTerminalRuleCall_1_2_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_2_2() { return cEqualsSignKeyword_1_2_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_1_2_3() { return cAlternatives_1_2_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_1_2_3_0() { return cIsInactiveAssignment_1_2_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_1_2_3_0_0() { return cIsInactiveInactiveKeyword_1_2_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_1_2_3_1() { return cGroup_1_2_3_1; }

		//type=ID
		public Assignment getTypeAssignment_1_2_3_1_0() { return cTypeAssignment_1_2_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_1_2_3_1_0_0() { return cTypeIDTerminalRuleCall_1_2_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_1_2_3_1_1() { return cAttributeAssignment_1_2_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_1_2_3_1_1_0() { return cAttributeIDTerminalRuleCall_1_2_3_1_1_0; }

		//("comment" comment=STRING)?
		public Group getGroup_2() { return cGroup_2; }

		//"comment"
		public Keyword getCommentKeyword_2_0() { return cCommentKeyword_2_0; }

		//comment=STRING
		public Assignment getCommentAssignment_2_1() { return cCommentAssignment_2_1; }

		//STRING
		public RuleCall getCommentSTRINGTerminalRuleCall_2_1_0() { return cCommentSTRINGTerminalRuleCall_2_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class FunctionModulePOJOTablesParameterElements implements IParserRuleAccess {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionModulePOJOTablesParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cIsInactiveAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final Keyword cIsInactiveInactiveKeyword_3_0_0 = (Keyword)cIsInactiveAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Assignment cTypeAssignment_3_1_0 = (Assignment)cGroup_3_1.eContents().get(0);
		private final RuleCall cTypeIDTerminalRuleCall_3_1_0_0 = (RuleCall)cTypeAssignment_3_1_0.eContents().get(0);
		private final Assignment cAttributeAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cAttributeIDTerminalRuleCall_3_1_1_0 = (RuleCall)cAttributeAssignment_3_1_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommentKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCommentAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCommentSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cCommentAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FunctionModulePOJOTablesParameter:
		//  "table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID) ("comment"
		//  comment=STRING)? ";";
		public ParserRule getRule() { return rule; }

		//"table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID) ("comment"
		//comment=STRING)? ";"
		public Group getGroup() { return cGroup; }

		//"table"
		public Keyword getTableKeyword_0() { return cTableKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//isInactive?="inactive"|type=ID attribute=ID
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//isInactive?="inactive"
		public Assignment getIsInactiveAssignment_3_0() { return cIsInactiveAssignment_3_0; }

		//"inactive"
		public Keyword getIsInactiveInactiveKeyword_3_0_0() { return cIsInactiveInactiveKeyword_3_0_0; }

		//type=ID attribute=ID
		public Group getGroup_3_1() { return cGroup_3_1; }

		//type=ID
		public Assignment getTypeAssignment_3_1_0() { return cTypeAssignment_3_1_0; }

		//ID
		public RuleCall getTypeIDTerminalRuleCall_3_1_0_0() { return cTypeIDTerminalRuleCall_3_1_0_0; }

		//attribute=ID
		public Assignment getAttributeAssignment_3_1_1() { return cAttributeAssignment_3_1_1; }

		//ID
		public RuleCall getAttributeIDTerminalRuleCall_3_1_1_0() { return cAttributeIDTerminalRuleCall_3_1_1_0; }

		//("comment" comment=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"comment"
		public Keyword getCommentKeyword_4_0() { return cCommentKeyword_4_0; }

		//comment=STRING
		public Assignment getCommentAssignment_4_1() { return cCommentAssignment_4_1; }

		//STRING
		public RuleCall getCommentSTRINGTerminalRuleCall_4_1_0() { return cCommentSTRINGTerminalRuleCall_4_1_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	
	
	private ModelElements pModel;
	private StructureElements pStructure;
	private StructureMappingElements pStructureMapping;
	private StructurePOJOMappingElements pStructurePOJOMapping;
	private StructureFieldPOJOMappingElements pStructureFieldPOJOMapping;
	private FunctionModuleElements pFunctionModule;
	private FunctionModuleMappingElements pFunctionModuleMapping;
	private FunctionModulePOJOMappingElements pFunctionModulePOJOMapping;
	private FunctionModulePOJOCallMappingElements pFunctionModulePOJOCallMapping;
	private FunctionModulePOJORequestResponseMappingElements pFunctionModulePOJORequestResponseMapping;
	private FunctionModulePOJOParameterMappingElements pFunctionModulePOJOParameterMapping;
	private FunctionModulePOJOImportingParameterElements pFunctionModulePOJOImportingParameter;
	private FunctionModulePOJOExportingParameterElements pFunctionModulePOJOExportingParameter;
	private FunctionModulePOJOChangingParameterElements pFunctionModulePOJOChangingParameter;
	private FunctionModulePOJOTablesParameterElements pFunctionModulePOJOTablesParameter;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public RFCMappingGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//  "package" packageName=STRING structures+=Structure* functionModules+=FunctionModule
	//  *; 
	//
	//
	//	  
	//	    
	//	    
	//
	//// ====== Structures ==============================================================================
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Structure:
	//  "structure" name=STRING "{" mapping=StructureMapping "}"; 
	//
	//// ====== Structures ==============================================================================
	public StructureElements getStructureAccess() {
		return (pStructure != null) ? pStructure : (pStructure = new StructureElements());
	}
	
	public ParserRule getStructureRule() {
		return getStructureAccess().getRule();
	}

	//StructureMapping:
	//  StructurePOJOMapping; 
	//
	//
	//	
	//
	//// --- POJO mapping -------------------------------------------------------------------------------
	public StructureMappingElements getStructureMappingAccess() {
		return (pStructureMapping != null) ? pStructureMapping : (pStructureMapping = new StructureMappingElements());
	}
	
	public ParserRule getStructureMappingRule() {
		return getStructureMappingAccess().getRule();
	}

	//StructurePOJOMapping:
	//  "class" className=ID "{" fields+=StructureFieldPOJOMapping* "}"; 
	//
	//// --- POJO mapping -------------------------------------------------------------------------------
	public StructurePOJOMappingElements getStructurePOJOMappingAccess() {
		return (pStructurePOJOMapping != null) ? pStructurePOJOMapping : (pStructurePOJOMapping = new StructurePOJOMappingElements());
	}
	
	public ParserRule getStructurePOJOMappingRule() {
		return getStructurePOJOMappingAccess().getRule();
	}

	//StructureFieldPOJOMapping:
	//  "field" name=STRING "=" type=ID attribute=ID ("comment" comment=STRING)? ";"; 
	//
	//
	//	              
	//
	//// ====== Function Modules ========================================================================
	public StructureFieldPOJOMappingElements getStructureFieldPOJOMappingAccess() {
		return (pStructureFieldPOJOMapping != null) ? pStructureFieldPOJOMapping : (pStructureFieldPOJOMapping = new StructureFieldPOJOMappingElements());
	}
	
	public ParserRule getStructureFieldPOJOMappingRule() {
		return getStructureFieldPOJOMappingAccess().getRule();
	}

	//FunctionModule:
	//  "function" "module" name=STRING "{" mapping=FunctionModuleMapping "}"; 
	//
	//// ====== Function Modules ========================================================================
	public FunctionModuleElements getFunctionModuleAccess() {
		return (pFunctionModule != null) ? pFunctionModule : (pFunctionModule = new FunctionModuleElements());
	}
	
	public ParserRule getFunctionModuleRule() {
		return getFunctionModuleAccess().getRule();
	}

	//FunctionModuleMapping:
	//  FunctionModulePOJOMapping; 
	//	
	// 
	//	
	//
	//// --- POJO mapping -------------------------------------------------------------------------------
	public FunctionModuleMappingElements getFunctionModuleMappingAccess() {
		return (pFunctionModuleMapping != null) ? pFunctionModuleMapping : (pFunctionModuleMapping = new FunctionModuleMappingElements());
	}
	
	public ParserRule getFunctionModuleMappingRule() {
		return getFunctionModuleMappingAccess().getRule();
	}

	//FunctionModulePOJOMapping:
	//  FunctionModulePOJOCallMapping|FunctionModulePOJORequestResponseMapping; 
	//
	//// --- POJO mapping -------------------------------------------------------------------------------
	public FunctionModulePOJOMappingElements getFunctionModulePOJOMappingAccess() {
		return (pFunctionModulePOJOMapping != null) ? pFunctionModulePOJOMapping : (pFunctionModulePOJOMapping = new FunctionModulePOJOMappingElements());
	}
	
	public ParserRule getFunctionModulePOJOMappingRule() {
		return getFunctionModulePOJOMappingAccess().getRule();
	}

	//FunctionModulePOJOCallMapping:
	//  "class" className=ID "{" parameters+=FunctionModulePOJOParameterMapping* "}";
	public FunctionModulePOJOCallMappingElements getFunctionModulePOJOCallMappingAccess() {
		return (pFunctionModulePOJOCallMapping != null) ? pFunctionModulePOJOCallMapping : (pFunctionModulePOJOCallMapping = new FunctionModulePOJOCallMappingElements());
	}
	
	public ParserRule getFunctionModulePOJOCallMappingRule() {
		return getFunctionModulePOJOCallMappingAccess().getRule();
	}

	//FunctionModulePOJORequestResponseMapping:
	//  "request" "class" requestClassName=ID "{" requestParameters+=
	//  FunctionModulePOJOParameterMapping* "}" "response" "class" responseClassName=ID "{"
	//  responseParameters+=FunctionModulePOJOParameterMapping* "}";
	public FunctionModulePOJORequestResponseMappingElements getFunctionModulePOJORequestResponseMappingAccess() {
		return (pFunctionModulePOJORequestResponseMapping != null) ? pFunctionModulePOJORequestResponseMapping : (pFunctionModulePOJORequestResponseMapping = new FunctionModulePOJORequestResponseMappingElements());
	}
	
	public ParserRule getFunctionModulePOJORequestResponseMappingRule() {
		return getFunctionModulePOJORequestResponseMappingAccess().getRule();
	}

	//FunctionModulePOJOParameterMapping:
	//  FunctionModulePOJOImportingParameter|FunctionModulePOJOExportingParameter|
	//  FunctionModulePOJOChangingParameter|FunctionModulePOJOTablesParameter;
	public FunctionModulePOJOParameterMappingElements getFunctionModulePOJOParameterMappingAccess() {
		return (pFunctionModulePOJOParameterMapping != null) ? pFunctionModulePOJOParameterMapping : (pFunctionModulePOJOParameterMapping = new FunctionModulePOJOParameterMappingElements());
	}
	
	public ParserRule getFunctionModulePOJOParameterMappingRule() {
		return getFunctionModulePOJOParameterMappingAccess().getRule();
	}

	//FunctionModulePOJOImportingParameter:
	//  "import" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
	//  isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
	//  ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
	//  "comment" comment=STRING)? ";";
	public FunctionModulePOJOImportingParameterElements getFunctionModulePOJOImportingParameterAccess() {
		return (pFunctionModulePOJOImportingParameter != null) ? pFunctionModulePOJOImportingParameter : (pFunctionModulePOJOImportingParameter = new FunctionModulePOJOImportingParameterElements());
	}
	
	public ParserRule getFunctionModulePOJOImportingParameterRule() {
		return getFunctionModulePOJOImportingParameterAccess().getRule();
	}

	//FunctionModulePOJOExportingParameter:
	//  "export" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
	//  isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
	//  ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
	//  "comment" comment=STRING)? ";";
	public FunctionModulePOJOExportingParameterElements getFunctionModulePOJOExportingParameterAccess() {
		return (pFunctionModulePOJOExportingParameter != null) ? pFunctionModulePOJOExportingParameter : (pFunctionModulePOJOExportingParameter = new FunctionModulePOJOExportingParameterElements());
	}
	
	public ParserRule getFunctionModulePOJOExportingParameterRule() {
		return getFunctionModulePOJOExportingParameterAccess().getRule();
	}

	//FunctionModulePOJOChangingParameter:
	//  "change" ("field" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)|
	//  isStructure?="structure" name=STRING "=" (isInactive?="inactive"|type=ID attribute=
	//  ID)|isTable?="table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID)) (
	//  "comment" comment=STRING)? ";";
	public FunctionModulePOJOChangingParameterElements getFunctionModulePOJOChangingParameterAccess() {
		return (pFunctionModulePOJOChangingParameter != null) ? pFunctionModulePOJOChangingParameter : (pFunctionModulePOJOChangingParameter = new FunctionModulePOJOChangingParameterElements());
	}
	
	public ParserRule getFunctionModulePOJOChangingParameterRule() {
		return getFunctionModulePOJOChangingParameterAccess().getRule();
	}

	//FunctionModulePOJOTablesParameter:
	//  "table" name=STRING "=" (isInactive?="inactive"|type=ID attribute=ID) ("comment"
	//  comment=STRING)? ";";
	public FunctionModulePOJOTablesParameterElements getFunctionModulePOJOTablesParameterAccess() {
		return (pFunctionModulePOJOTablesParameter != null) ? pFunctionModulePOJOTablesParameter : (pFunctionModulePOJOTablesParameter = new FunctionModulePOJOTablesParameterElements());
	}
	
	public ParserRule getFunctionModulePOJOTablesParameterRule() {
		return getFunctionModulePOJOTablesParameterAccess().getRule();
	}

	//terminal ID:
	//  "^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//  "0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//  "\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" |
	//  "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//  "/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//  "//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//  (" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//  .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
