/*
* generated by Xtext
*/
package net.sf.rcer.rfcgen.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.sf.rcer.rfcgen.services.RFCMappingGrammarAccess;

public class RFCMappingParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RFCMappingGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.sf.rcer.rfcgen.parser.antlr.internal.InternalRFCMappingParser createParser(XtextTokenStream stream) {
		return new net.sf.rcer.rfcgen.parser.antlr.internal.InternalRFCMappingParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public RFCMappingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RFCMappingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
